In [2]:
!pip install numpy

In [3]:
import numpy as np

In [5]:
array_one = np.array([0,1,3,5,7,9])
array_one

array([0, 1, 3, 5, 7, 9])

In [6]:
num = [11,22,33,44,55,66,77]
array_two = np.array(num)
array_two

array([11, 22, 33, 44, 55, 66, 77])

In [8]:
array_of_zeroes = np.zeros((2,3))
array_of_zeroes

array([[0., 0., 0.],
       [0., 0., 0.]])

In [9]:
array_of_ones = np.ones((3,2))
array_of_ones

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [10]:
array_of_ones = np.ones((3,2), dtype = np.int32)
array_of_ones

array([[1, 1],
       [1, 1],
       [1, 1]], dtype=int32)

In [11]:
array_empty = np.empty((3,2))
array_empty

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [12]:
array_eye = np.eye(4)
array_eye

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [14]:
array_of_evens = np.arange(2,24,2)
array_of_evens

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22])

In [15]:
array_of_floats = np.arange(1, 3, 0.3)
array_of_floats

array([1. , 1.3, 1.6, 1.9, 2.2, 2.5, 2.8])

In [17]:
#tuple
array_2D = np.array([(3,4,6), (2,1,6)])
array_2D

array([[3, 4, 6],
       [2, 1, 6]])

In [18]:
array_2D.shape

(2, 3)

In [19]:
np.arange(8)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [20]:
#reshape - need to have the right number of elements
array_nd = np.arange(8).reshape(2,4)
array_nd

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [21]:
#this will throw an error because the shape is (2,3) not (2,4)
array_nd = np.arange(6).reshape(2,4)

ValueError: cannot reshape array of size 6 into shape (2,4)

In [22]:
array_nd

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [23]:
#numpy array which is same as array_nd
array_ones = np.ones_like(array_nd)
array_ones

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])